
// Code generated by mtgroup-generator.
package dal

import (
	"time"
		"database/sql"
		"demo/internal/types"
)

// Make sure not to overwrite this file after you generated it because all your edits would be lost!

const (

	sqlGetDeploy = `
	SELECT
		id,
		config,
		cpu_units,
		created_at,
		memory_mb,
		name,
		price,
		state,
		storage_mb,
		user_id
	FROM
		deploys
	WHERE
		id=:id AND
		isolated_entity_id=:isolated_entity_id AND
		NOT deleted
	`

	sqlGetMyDeployID = `
	SELECT
		id
	FROM
		deploys
	WHERE
		created_by=:created_by AND
		isolated_entity_id=:isolated_entity_id AND
		NOT deleted AND
		bound
	`


	sqlAddDeploy = `
	INSERT INTO deploys(
		config,
		cpu_units,
		created_at,
		memory_mb,
		name,
		price,
		state,
		storage_mb,
		user_id,
		id,
		created_by,
		isolated_entity_id
	) VALUES (
		:config,
		:cpu_units,
		:created_at,
		:memory_mb,
		:name,
		:price,
		:state,
		:storage_mb,
		:user_id,
		:id,
		:created_by,
		:isolated_entity_id
	)
	RETURNING
		id
	`

	sqlBindDeployToProfile = `
	UPDATE
		deploys
	SET
		bound=true
	WHERE
		id=:id AND
		created_by=:created_by AND
		isolated_entity_id=:isolated_entity_id AND
		NOT deleted AND
		NOT bound
	`

	sqlDeleteDeploy = `
	UPDATE
		deploys
	SET
		deleted=true,
		deleted_at=:deleted_at,
		deleted_by=:deleted_by
	WHERE
		id=:id AND
		isolated_entity_id=:isolated_entity_id AND
		NOT deleted
	`

	sqlEditDeploy = `
	UPDATE
		deploys
	SET
		config=:config,
		cpu_units=:cpu_units,
		memory_mb=:memory_mb,
		name=:name,
		price=:price,
		state=:state,
		storage_mb=:storage_mb,
		user_id=:user_id
	WHERE
		id=:id AND
		isolated_entity_id=:isolated_entity_id AND
		NOT deleted
	`
	
	sqlListDeploy = `
	SELECT
		id,
		config,
		cpu_units,
		created_at,
		memory_mb,
		name,
		price,
		state,
		storage_mb,
		user_id
	FROM
		deploys
	WHERE
		isolated_entity_id=:isolated_entity_id AND
		NOT deleted
	`
	sqlListDeployCount = `
	SELECT
		COUNT(*)
	FROM
		deploys
	WHERE
		isolated_entity_id=:isolated_entity_id AND
		NOT deleted
	`
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
					sqlGetUserForDeployLazyLoading = `
	SELECT
		id,
		balance,
		name,
		role
	FROM
		users
	WHERE
		id=:id AND
		isolated_entity_id=:isolated_entity_id
	`
			
	
)

type (
    argGetDeploy struct {
        ID sql.NullString `db:"id"`
			IsolatedEntityID string `db:"isolated_entity_id"`
    }

	argGetMyDeployID struct {
			CreatedBy string `db:"created_by"`
			IsolatedEntityID string `db:"isolated_entity_id"`
    }
	argAddDeploy struct {
							ID string `db:"id"`
							Config string `db:"config"`
							CpuUnits types.Decimal `db:"cpu_units"`
							CreatedAt *time.Time `db:"created_at"`
							MemoryMb int32 `db:"memory_mb"`
							Name string `db:"name"`
							Price types.Decimal `db:"price"`
							State string `db:"state"`
							StorageMb int32 `db:"storage_mb"`
					UserID interface{} `db:"user_id"`
			CreatedBy string `db:"created_by"`
			IsolatedEntityID string `db:"isolated_entity_id"`
	}
	argBindDeployToProfile struct {
		ID string `db:"id"`
			CreatedBy string `db:"created_by"`
			IsolatedEntityID string `db:"isolated_entity_id"`
	}
	argEditDeploy struct {
						ID string `db:"id"`
						Config string `db:"config"`
						CpuUnits types.Decimal `db:"cpu_units"`
						CreatedAt *time.Time `db:"created_at"`
						MemoryMb int32 `db:"memory_mb"`
						Name string `db:"name"`
						Price types.Decimal `db:"price"`
						State string `db:"state"`
						StorageMb int32 `db:"storage_mb"`
					UserID interface{} `db:"user_id"`
			IsolatedEntityID string `db:"isolated_entity_id"`
	}
	argDeleteDeploy struct {
		ID string `db:"id"`
		DeletedAt *time.Time `db:"deleted_at"`
		DeletedBy string `db:"deleted_by"`
			IsolatedEntityID string `db:"isolated_entity_id"`
	}
)