
// Code generated by mtgroup-generator.
package app

import (
	"testing"

	"github.com/golang/mock/gomock"
	"github.com/powerman/check"
)

// Make sure not to overwrite this file after you generated it because all your edits would be lost!


func TestGetExample(tt *testing.T) {
	t := check.T(tt)
	t.Parallel()
	ctrl := gomock.NewController(t)
	defer ctrl.Finish()

	mockRepo := NewMockRepo(ctrl)
	rulesSet := NewMockRulesSet(ctrl)

	a := New(mockRepo, rulesSet)

	rulesSet.EXPECT().GetExampleAccessManager(gomock.Any()).Return(true) 
		mockRepo.EXPECT().GetExample(gomock.Any(), gomock.Any()).Return(testExample1, nil)
		b, err := a.GetExample(profile, testExample1.ID)
		t.Nil(err)
		t.DeepEqual(testExample1, b)
}

func TestAddExample(tt *testing.T) {
	t := check.T(tt)
	t.Parallel()
	ctrl := gomock.NewController(t)
	defer ctrl.Finish()

	mockRepo := NewMockRepo(ctrl)
	rulesSet := NewMockRulesSet(ctrl)

	a := New(mockRepo, rulesSet)

	rulesSet.EXPECT().AddExampleAccessManager(gomock.Any()).Return(true)
		mockRepo.EXPECT().AddExample(gomock.Any(), gomock.Any(), gomock.Any()).Return(testExample1, nil)
		b, err := a.AddExample(profile, testExample1)
		t.Nil(err)
		t.DeepEqual(testExample1, b)
}

func TestDeleteExample(tt *testing.T) {
	t := check.T(tt)
	t.Parallel()
	ctrl := gomock.NewController(t)
	defer ctrl.Finish()

	mockRepo := NewMockRepo(ctrl)
	rulesSet := NewMockRulesSet(ctrl)

	a := New(mockRepo, rulesSet)

	rulesSet.EXPECT().DeleteExampleAccessManager(gomock.Any()).Return(true)
		mockRepo.EXPECT().DeleteExample(gomock.Any(), gomock.Any(), gomock.Any()).Return(nil)
		err := a.DeleteExample(profile, testExample1.ID)
		t.Nil(err)
}

func TestEditExample(tt *testing.T) {
	t := check.T(tt)
	t.Parallel()
	ctrl := gomock.NewController(t)
	defer ctrl.Finish()

	mockRepo := NewMockRepo(ctrl)
	rulesSet := NewMockRulesSet(ctrl)

	a := New(mockRepo, rulesSet)

	rulesSet.EXPECT().EditExampleAccessManager(gomock.Any()).Return(true)
		mockRepo.EXPECT().EditExample(gomock.Any(), gomock.Any(), gomock.Any()).Return(testExample2, nil)
		b, err := a.EditExample(profile, testExample1.ID, testExample1)
		t.Nil(err)
			t.DeepEqual(testExample2, b)
}

func TestListExample(tt *testing.T) {
	t := check.T(tt)
	t.Parallel()
	ctrl := gomock.NewController(t)
	defer ctrl.Finish()

	mockRepo := NewMockRepo(ctrl)
	rulesSet := NewMockRulesSet(ctrl)

	a := New(mockRepo, rulesSet)

	rulesSet.EXPECT().ListExampleAccessManager(gomock.Any()).Return(true)
		mockRepo.EXPECT().ListExample(gomock.Any(), gomock.Any()).Return(testExamples, 2, []string{}, nil)
		b, count, _, err := a.ListExample(profile, listParams)
		t.Nil(err)
		t.Equal(2, count)
		t.DeepEqual(testExamples, b)
}
