// Code generated by mtgroup-generator.  
package app

import (
		"demo/internal/types"
)

// Make sure not to overwrite this file after you generated it because all your edits would be lost!
type Example struct {
		CpuUnits types.Decimal
		ID string
		MemoryMb int32
		Name string
		Price types.Decimal
		StorageMb int32
		User *User
}
		func (a *app) GetExample(prof Profile, id string) (*Example, error) {
			if !a.rulesSet.GetExampleAccessManager(prof) {
				return nil, ErrAccessDenied
			}
			return a.repo.GetExample(id, prof.IsolatedEntityID)
		}
		func (a *app) AddExample(prof Profile, m *Example) (*Example, error) {
			if !a.rulesSet.AddExampleAccessManager(prof) {
				return nil, ErrAccessDenied
			}
			return a.repo.AddExample(prof.ID, prof.IsolatedEntityID, m)
		}
		func (a *app) DeleteExample(prof Profile, id string) error {
			if !a.rulesSet.DeleteExampleAccessManager(prof) {
				return ErrAccessDenied
			}
			return a.repo.DeleteExample(id, prof.ID, prof.IsolatedEntityID)
		}
		func (a *app) EditExample(prof Profile, id string, m *Example) (*Example, error) {
			if !a.rulesSet.EditExampleAccessManager(prof) {
				return nil, ErrAccessDenied
			}
			return a.repo.EditExample(id, prof.IsolatedEntityID, m)
		}
		func (a *app) ListExample(prof Profile, params *ListParams) ([]*Example, int, []string, error) {
			if !a.rulesSet.ListExampleAccessManager(prof) {
				return nil, 0, nil, ErrAccessDenied
			}
			return a.repo.ListExample(prof.IsolatedEntityID, params)
		}
       



