// Code generated by mtgroup-generator.
package app

// Make sure not to overwrite this file after you generated it because all your edits would be lost!

type RulesSet interface {
	
			GetDeployAccessManager(Profile) bool
			AddDeployAccessManager(Profile) bool
			DeleteDeployAccessManager(Profile) bool
			EditDeployAccessManager(Profile) bool
			ListDeployAccessManager(Profile) bool
    
			GetExampleAccessManager(Profile) bool
			AddExampleAccessManager(Profile) bool
			DeleteExampleAccessManager(Profile) bool
			EditExampleAccessManager(Profile) bool
			ListExampleAccessManager(Profile) bool
    
			GetTransactionAccessManager(Profile) bool
			AddTransactionAccessManager(Profile) bool
			DeleteTransactionAccessManager(Profile) bool
			EditTransactionAccessManager(Profile) bool
			ListTransactionAccessManager(Profile) bool
    
			GetUserAccessManager(Profile) bool
			AddUserAccessManager(Profile) bool
			DeleteUserAccessManager(Profile) bool
			EditUserAccessManager(Profile) bool
			ListUserAccessManager(Profile) bool
    
}