// Code generated by mtgroup-generator.  
package app

import (
		"demo/internal/types"
)

// Make sure not to overwrite this file after you generated it because all your edits would be lost!
type User struct {
		Balance types.Decimal
		ID string
		Name string
		Role string
}
		func (a *app) GetUser(prof Profile, id string) (*User, error) {
			if !a.rulesSet.GetUserAccessManager(prof) {
				return nil, ErrAccessDenied
			}
			return a.repo.GetUser(id, prof.IsolatedEntityID)
		}
		func (a *app) AddUser(prof Profile, m *User) (*User, error) {
			if !a.rulesSet.AddUserAccessManager(prof) {
				return nil, ErrAccessDenied
			}
			return a.repo.AddUser(prof.ID, prof.IsolatedEntityID, m)
		}
		func (a *app) DeleteUser(prof Profile, id string) error {
			if !a.rulesSet.DeleteUserAccessManager(prof) {
				return ErrAccessDenied
			}
			return a.repo.DeleteUser(id, prof.ID, prof.IsolatedEntityID)
		}
		func (a *app) EditUser(prof Profile, id string, m *User) (*User, error) {
			if !a.rulesSet.EditUserAccessManager(prof) {
				return nil, ErrAccessDenied
			}
			return a.repo.EditUser(id, prof.IsolatedEntityID, m)
		}
		func (a *app) ListUser(prof Profile, params *ListParams) ([]*User, int, []string, error) {
			if !a.rulesSet.ListUserAccessManager(prof) {
				return nil, 0, nil, ErrAccessDenied
			}
			return a.repo.ListUser(prof.IsolatedEntityID, params)
		}
    



