// Code generated by mtgroup-generator.
package authorization

import (
	"demo/internal/app"
)

// Make sure not to overwrite this file after you generated it because all your edits would be lost!

type rulesSet struct {
	rules Rules
}

func NewRulesSet() *rulesSet {
	return &rulesSet{
		rules: newRules(),
	}
}


		func (rs *rulesSet) GetDeployAccessManager(prof app.Profile) bool {
			return true
		}
		func (rs *rulesSet) AddDeployAccessManager(prof app.Profile) bool {
			return true
		}
		func (rs *rulesSet) DeleteDeployAccessManager(prof app.Profile) bool {
			return true
		}
		func (rs *rulesSet) EditDeployAccessManager(prof app.Profile) bool {
			return true
		}
		func (rs *rulesSet) ListDeployAccessManager(prof app.Profile) bool {
			return true
		}

		func (rs *rulesSet) GetExampleAccessManager(prof app.Profile) bool {
			return true
		}
		func (rs *rulesSet) AddExampleAccessManager(prof app.Profile) bool {
			return true
		}
		func (rs *rulesSet) DeleteExampleAccessManager(prof app.Profile) bool {
			return true
		}
		func (rs *rulesSet) EditExampleAccessManager(prof app.Profile) bool {
			return true
		}
		func (rs *rulesSet) ListExampleAccessManager(prof app.Profile) bool {
			return true
		}

		func (rs *rulesSet) GetTransactionAccessManager(prof app.Profile) bool {
			return true
		}
		func (rs *rulesSet) AddTransactionAccessManager(prof app.Profile) bool {
			return true
		}
		func (rs *rulesSet) DeleteTransactionAccessManager(prof app.Profile) bool {
			return true
		}
		func (rs *rulesSet) EditTransactionAccessManager(prof app.Profile) bool {
			return true
		}
		func (rs *rulesSet) ListTransactionAccessManager(prof app.Profile) bool {
			return true
		}

		func (rs *rulesSet) GetUserAccessManager(prof app.Profile) bool {
			return true
		}
		func (rs *rulesSet) AddUserAccessManager(prof app.Profile) bool {
			return true
		}
		func (rs *rulesSet) DeleteUserAccessManager(prof app.Profile) bool {
			return true
		}
		func (rs *rulesSet) EditUserAccessManager(prof app.Profile) bool {
			return true
		}
		func (rs *rulesSet) ListUserAccessManager(prof app.Profile) bool {
			return true
		}
